metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.198, mac: '00:0C:29:D8:0B:08', disk: sda, network_interface: ens192}
        metal1: {ansible_host: 192.168.0.167, mac: '00:0C:29:88:CC:4A', disk: sda, network_interface: ens192}
        metal2: {ansible_host: 192.168.0.249, mac: '00:0C:29:7A:3C:84', disk: sda, network_interface: ens192} 


    workers:
      hosts:
        metal3: {ansible_host: 192.168.0.124, mac: '00:0C:29:D1:EE:C4', disk: sda, network_interface: ens192}
        
